name: async_await_cancel
description: async/await cancellation demo
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
flutter:
  uses-material-design: true

dependencies:
  async: 2.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: 5.1.0
