name: async_await_cancel
description: async/await cancellation demo
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"
flutter:
  uses-material-design: true

dependencies:
  async: 2.11.0
  flutter:
    sdk: flutter
